message(STATUS "Remote building selected. Skipping everything except IDE initialization...")
if("${USE_IDE}" STREQUAL "eclipse")
    message(WARNING "Remote Execution is not supported in Eclipse! Use VSCode or the Command line!")
elseif("${USE_IDE}" STREQUAL "vscode")
    if("${TOOLCHAIN}" STREQUAL "docker")
        message(STATUS "Generating project files for Docker-based development in VSCode...")
        configure_file(${CMAKE_CONFIG_DIR}/vscode/c_cpp_properties.remote.json.in ${PROJECT_SOURCE_DIR}/.vscode/c_cpp_properties.json @ONLY)
        configure_file(${CMAKE_CONFIG_DIR}/vscode/extensions.remote.json.in ${PROJECT_SOURCE_DIR}/.vscode/extensions.json @ONLY)
        configure_file(${CMAKE_CONFIG_DIR}/vscode/launch.remote.docker.json.in ${PROJECT_SOURCE_DIR}/.vscode/launch.json @ONLY)
        configure_file(${CMAKE_CONFIG_DIR}/vscode/settings.remote.json.in ${PROJECT_SOURCE_DIR}/.vscode/settings.json @ONLY)
        configure_file(${CMAKE_CONFIG_DIR}/vscode/tasks.remote.docker.json.in ${PROJECT_SOURCE_DIR}/.vscode/tasks.json @ONLY)
    elseif("${TOOLCHAIN}" STREQUAL "vm")
        message(STATUS "Generating project files for VM-based development in VSCode...")
        configure_file(${CMAKE_CONFIG_DIR}/vscode/c_cpp_properties.remote.json.in ${PROJECT_SOURCE_DIR}/.vscode/c_cpp_properties.json @ONLY)
        configure_file(${CMAKE_CONFIG_DIR}/vscode/extensions.remote.json.in ${PROJECT_SOURCE_DIR}/.vscode/extensions.json @ONLY)
        configure_file(${CMAKE_CONFIG_DIR}/vscode/launch.remote.vm.json.in ${PROJECT_SOURCE_DIR}/.vscode/launch.json @ONLY)
        configure_file(${CMAKE_CONFIG_DIR}/vscode/settings.remote.json.in ${PROJECT_SOURCE_DIR}/.vscode/settings.json @ONLY)
        configure_file(${CMAKE_CONFIG_DIR}/vscode/tasks.remote.vm.json.in ${PROJECT_SOURCE_DIR}/.vscode/tasks.json @ONLY)
    else()
        message(WARNING "No IDE projects generated.")
    endif()
else()
    message(STATUS "No IDE projects generated.")
endif()
